# qBittorrent parameters
qbt:
  host: 'localhost:8080'
  user: 'username'
  pass: 'password'

directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/> #Output directory of cross-seed 
  # root_dir var: </your/path/here/> #Root downloads directory used to check for orphaned files
  # <OPTIONAL> remote_dir var: </your/path/here/> # Path of docker host mapping of root_dir
  cross_seed: '/your/path/here/'
  root_dir:  '/data/torrents/'
  remote_dir: '/mnt/user/data/torrents/'

# Category/Pathing Parameters
cat:
  # <Category Name> : <save_path> #Path of your save directory. Can be a keyword or full path
  movies: '/data/torrents/Movies'
  tv: 'TV'

# Tag Parameters
tags:
  # <Tracker URL Keyword>: <Tag Name>
  beyond-hd: Beyond-HD
  privatehd: PrivateHD
  animebytes.tv: AnimeBytes
  avistaz: Avistaz
  landof.tv: BroadcasTheNet
  passthepopcorn: PassThePopcorn
  torrentleech: TorrentLeech
  tleechreload: TorrentLeech
  gazellegames: GGn
  blutopia: Blutopia
  hdts: HDTorrents
  tv-vault: TV-Vault
  cartoonchaos: CartoonChaos
