# qBittorrent parameters
qbt:
  host: 'localhost:8080'
  user: 'username'
  pass: 'password'
remote_dir:
  #'Docker container path of root save directory' : 'Local path of root save directory'
  #<'/container/path/data/'> : <'/host/path/data/'>
  '/data/torrents/' : '/mnt/cache/data/torrents/'
directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/>
  cross_seed: '/your/path/here/'
# Category/Pathing Parameters
cat:
  # <File path keyword>: <Category Name>
  movies: movies
  tv: tv
# Tag Parameters
tags:
  # <Tracker URL Keyword>: <Tag Name>
  beyond-hd: Beyond-HD
  privatehd: PrivateHD
  animebytes.tv: AnimeBytes
  avistaz: Avistaz
  landof.tv: BroadcasTheNet
  passthepopcorn: PassThePopcorn
  torrentleech: TorrentLeech
  tleechreload: TorrentLeech
  gazellegames: GGn
  blutopia: Blutopia
  hdts: HDTorrents
  tv-vault: TV-Vault
  cartoonchaos: CartoonChaos
