# qBittorrent parameters
qbt:
  host: 'localhost:8080'
  user: 'username'
  pass: 'password'

directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/>
  cross_seed: '/your/path/here/'
# Category/Pathing Parameters
cat:
  # <Category Name> : <save_path> #Path of your save directory. Can be a keyword or full path
  movies: '/data/torrents/Movies'
  tv: 'TV'

# Tag Parameters
tags:
  # <Tracker URL Keyword>: <Tag Name>
  beyond-hd: Beyond-HD
  privatehd: PrivateHD
  animebytes.tv: AnimeBytes
  avistaz: Avistaz
  landof.tv: BroadcasTheNet
  passthepopcorn: PassThePopcorn
  torrentleech: TorrentLeech
  tleechreload: TorrentLeech
  gazellegames: GGn
  blutopia: Blutopia
  hdts: HDTorrents
  tv-vault: TV-Vault
  cartoonchaos: CartoonChaos
